export const REQUEST_TOKENS = 'REQUEST_TOKENS';
export const RECEIVE_TOKENS_AND_USERDETAILS = 'RECEIVE_TOKENS_AND_USERDETAILS';
export const REMOVE_TOKENS_AND_USERDETAILS = 'REMOVE_TOKENS_AND_USERDETAILS';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_LOGIN_EMAIL = 'SET_LOGIN_EMAIL';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
export const RESET_STORE = 'RESET_STORE';